version: "3.8"

services:
  # Aplicación Node.js
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlserver://74.208.227.171:1433;database=parcela_db;user=sa;password=ContrasenaSegura123!;encrypt=true;trustServerCertificate=true
      - MONGO_URI=mongodb+srv://admin:TJkbAFEVPHP2krAk@parcelasbd.ubiwgfs.mongodb.net/parcelas
      - API_EXTERNAL_URL=https://sensores-async-api.onrender.com/api/sensors/all
      - JWT_SECRET=desarrollo_jwt_secret_123
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
